# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: 无忧行签到

on:
  schedule:
    - cron: '00 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: autocheckin-py3.9
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache pip modules
        uses: actions/cache@v2
        env:
          cache-name: selfcheck.json
        with:
          path: ~/.cache/pip
          key: ${{ env.cache-name }}

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
      - name: jegotrip 无忧行签到
        env:
          USERID: ${{secrets.USERID}}
        run: |
          python jegotrip.py
